core/urls.py
from django.urls import path

from . import views

app_name = "core"


urlpatterns = [
    path("", views.home, name="home"),
    path("play/<uuid:uuid>", views.supermorpion, name="play"),
    path("new-game", views.new_game, name="new-game"),
    path("rules", views.rules, name="rules"),
    path("credits", views.credits_view, name="credits"),
    path("legals", views.legals, name="legals"),
]

supermorpion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [path("admin/", admin.site.urls), path("", include("core.urls"))]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}SuperMorpion{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <div class="footer">
        <p class="footer-left"><a href="{% url 'core:home' %}">Home</a></p>
        <p class="footer-left"><a href="{% url 'core:credits' %}">Credits</a></p>
        <p class="footer-left"><a href="{% url 'core:legals' %}">Legals</a></p>
        <p class="footer-right"><a href="https://github.com/nanoy42/supermorpion">Github</a></p>
        <p class="footer-right">Made with ❤ by Nanoy</p>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    {% block extrascript %}{% endblock %}
</body>

</html>

templates/credits.html
{% extends 'base.html' %}
{% block title %}Credits - SuperMorpion{% endblock %}
{% block content %}
<center>
    <h1>SuperMorpion</h1>
    <p>This game was made with ❤ by Nanoy</p>
    <p>You can find the source code on github : <a
            href="https://github.com/nanoy42/supermorpion">https://github.com/nanoy42/supermorpion</a></p>
    <p>The code is distributed under the GNU General Public License v3</p>
    <p>This game is dedicated to my grandfather, Michel Pelet, a real life model.</p>
    <button class="btn big-btn" onclick="location.href='{% url 'core:home' %}'">Home</button>
</center>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
<center>
    <h1>SuperMorpion</h1>
    <p>Welcome on SuperMorpion online game. SuperMorpion is a bigger (and more interesting) version of the tic tac toe.
    </p>
    <button class="btn big-btn" onclick="location.href='{% url 'core:new-game' %}'">New game</button>
    <button class="btn big-btn" onclick="location.href='{% url 'core:rules' %}'">Rules</button>
    <button class="btn big-btn" onclick="location.href='{% url 'core:credits' %}'">Credits</button>
</center>
{% endblock %}

templates/legals.html
{% extends 'base.html' %}
{% block title %}Legals - SuperMorpion{% endblock %}
{% block content %}
<center>
    <h1>SuperMorpion</h1>
    <p>Web editor and hosting : Yoann Pietri (contact <a href="mailot:me@nanoy.fr">me@nanoy.fr</a>)</p>
    <button class="btn big-btn" onclick="location.href='{% url 'core:home' %}'">Home</button>
</center>
{% endblock %}

templates/new_game.html
{% extends 'base.html' %}
{% block content %}
<center>
    <h1>SuperMorpion</h1>
    <p>Enjoy your game</p>
    <p>X url : <a href="{% url 'core:play' x_uuid %}"
            target="_blank">https://{{ request.get_host }}{% url 'core:play' x_uuid %}</a></p>
    <p>O url : <a href="{% url 'core:play' o_uuid %}"
            target="_blank">https://{{ request.get_host }}{% url 'core:play' o_uuid %}</a></p>
    <button class="btn big-btn" onclick="location.href='{% url 'core:home' %}'">Home</button>
</center>
{% endblock %}

templates/rules.html
{% extends 'base.html' %}
{% block content %}
<center>
    <h1>SuperMorpion</h1>
    <p>The game is composed by 91 cases. Each block of 9 cases, from now on reffered as a big case, is a classic
        tic-tac-toe. The group of the 9 big cases is itself a tic-tac-toe.</p>
    <p>In order to win, the player must complete a line of 3 big cases (horizontally, vertically or diagonally). In
        order to win a big case, a player must complete a line of 3 cases (horizontally, vertically or diagonally)
        inside the big case.</p>
    <p>The X player plays first. He must play in the central big case. Then the O player must play in the big case
        corresponding to the small case X has played (eg if X plays in the middle-left case of the central big case,
        them the O player must play in te middle-left big case). A player cannot play in a complete big case, so in the
        case the player should play in such a big case, he can play in any big case.</p>
    <button class="btn big-btn" onclick="location.href='{% url 'core:home' %}'">Home</button>
</center>
{% endblock %}

templates/supermorpion.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Game - SuperMorpion{% endblock %}
{% block content %}
{% csrf_token %}
<center>
    <h1>Supermorpion</h1>
    <h2>You are the {% if player == 1 %}X{% else %}O{% endif %} player</h2>
    {% if finished %}
    {% if player == game_owner %}
    <h3 id="player-help">You won</h3>
    {% else %}
    <h3 id="player-help">{% if player == 1 %}O{% else %}X{% endif %} player won</h3>
    {% endif %}
    {% else %}
    {% if player == next_player %}
    <h3 id="player-help">You play in {{next_case}}</h3>
    {% else %}
    <h3 id="player-help">{% if player == 1 %}O{% else %}X{% endif %} player plays in {{next_case}}</h3>
    {% endif %}
    {% endif %}
    <h3 id="error" class="error"></h3>
    <table>
        {% for line in lines %}
        <tr {% if forloop.counter|divisibleby:3 %}class="space-down" {% endif %}>
            {% for elem in line %}
            <td {% if forloop.counter|divisibleby:3 %}class="space-right" {% endif %}>
                <button id="{{forloop.parentloop.counter0}}{{forloop.counter0}}" class="case btn morpion-btn"
                    data-line="{{forloop.parentloop.counter0}}"
                    data-elem="{{forloop.counter0}}">{% if elem == 1 %}X{% elif elem == 2 %}O{% endif %}</button>
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </table>

    {% if finished %}
    <h3 id="other">Game is finished. <a href="{% url 'core:home' %}">Home</a>.</h3>
    {% else %}
    <h3 id="other"></h3>
    {% endif %}
</center>
{% endblock %}
{% block extrascript %}
<script>
    let player = {{ player }};
    let player_letter = {% if player == 1 %}"X"{% else %} "O"{% endif %};
    let other_player_letter = {% if player == 1 %}"O"{% else %} "X"{% endif %};
    let uuid = "{{uuid}}";
    let id = {{ id }};
    let last_big_case = {{ last_big_case }};
    let last_line_case = {{ last_line_case }};
    let last_case = {{ last_case }};
    let next_player = {{ next_player }};
    let inactive_cases = [];
    let next_big_case = {{ next_big_case }};
    {% for elem in inactive_cases %}
    inactive_cases.push({{ elem }});
    {% endfor %}
    end_message = "Game is finished. <a href=\"{% url 'core:home' %}\">Home</a>.";
</script>
<script>

    function lines_to_blocks(line, elem) {
        let offset = 0;
        if (line >= 6) {
            offset = 2
        } else if (line >= 3) {
            offset = 1
        }

        let offset2 = 0;
        if (elem >= 6) {
            offset2 = 2;
        } else if (elem >= 3) {
            offset2 = 1;
        }

        let big_case = 3 * offset + offset2;
        let line_case = line - 3 * offset;
        let elem_case = elem - 3 * offset2;
        return [big_case, line_case, elem_case];
    }

    function blocks_to_id(big_case, line_case, elem_case) {
        let offset = 0;
        if (big_case >= 6) {
            offset = 2
        } else if (big_case >= 3) {
            offset = 1
        }

        line = line_case + 3 * offset;
        elem = elem_case + 3 * (big_case % 3);
        return line.toString() + elem.toString();
    }

    function block_block(big_case) {
        for (var i = 0; i < 3; i++) {
            for (var j = 0; j < 3; j++) {
                $("#" + blocks_to_id(big_case, i, j)).addClass("inactive");
            }
        }
    }

    function active_block(big_case) {
        $(".case").removeClass("block-active");
        $(".case").addClass("block-inactive");
        for (var i = 0; i < 3; i++) {
            for (var j = 0; j < 3; j++) {
                $("#" + blocks_to_id(big_case, i, j)).removeClass("block-inactive");
                $("#" + blocks_to_id(big_case, i, j)).addClass("block-active");
            }
        }
    }

    $(document).ready(function () {
        var case_html = $("#" + blocks_to_id(last_big_case, last_line_case, last_case));
        case_html.addClass("active");
        if (player == next_player) {
            if (next_big_case == -1) {
                active_block(4);
            } else if (next_big_case == -2) {
                $(".case").addClass("block-active");
                $(".case").removeClass("block-inactive");
            } else {
                active_block(next_big_case);
            }
        } else {
            $(".case").addClass("block-inactive");
        }

        for (index = 0; index < inactive_cases.length; index++) {
            block_block(inactive_cases[index]);
        }

        var chatSocket = new WebSocket(
            'ws://' + window.location.host +
            '/ws/play-move/' + id);

        chatSocket.onmessage = function (e) {
            var data = JSON.parse(e.data);
            if (data["type"] == "response") {
                if (data["success"]) {
                    $(".case").removeClass("block-active");
                    $(".case").addClass("block-inactive");
                    $(".active").removeClass("active");
                    $("#player-help").html(other_player_letter + " player plays in " + data["next_case"]);
                    $("#error").html("");
                    case_html.html(player_letter);
                    case_html.addClass("active");
                    case_html.removeClass("hovering");
                } else {
                    $("#error").html(data["msg"]);
                }
            } else if (data["type"] == "announce") {
                if (data["next_player"] == player) {
                    $("#player-help").html("You play in " + data["next_case"]);
                    $("#error").html("");
                    console.log(data["next_big_case"]);
                    if (data["next_big_case"] == -2) {
                        $(".case").addClass("block-active");
                        $(".case").removeClass("block-inactive");
                    } else {
                        active_block(data["next_big_case"]);
                    }
                    case_html = $("#" + blocks_to_id(data["big_case"], data["line_case"], data["case"]));
                    $(".active").removeClass("active");
                    case_html.html(other_player_letter);
                    case_html.addClass("active");
                    case_html.removeClass("hovering");
                }
            } else if (data["type"] == "block") {
                block_block(data["big_case"]);
            } else if (data["type"] == "finished") {
                for (var i = 0; i < 9; i++) {
                    block_block(i);
                }
                $("#other").html(end_message);
                if (data["player"] == player) {
                    $("#player-help").html("You won");
                } else {
                    $("#player-help").html(other_player_letter + " player won");
                }
            } else {
                console.error("Unknown message");
            }
        };

        chatSocket.onclose = function (e) {
            $("#other").html('Connection to server lost. <a href="">Reload</a>');
        };

        $(".case").hover(function () {
            if ($(this).html() == "" && !$(this).hasClass("inactive") && !$(this).hasClass("block-inactive")) {
                $(this).html(player_letter);
                $(this).addClass("hovering");
            }
        }, function () {
            if ($(this).hasClass("hovering")) {
                $(this).html("");
                $(this).removeClass("hovering");
            }
        });
        $(".case").click(function () {
            var line = $(this).attr("data-line");
            var elem = $(this).attr("data-elem");
            var blocks = lines_to_blocks(line, elem);
            case_html = $(this);
            chatSocket.send(JSON.stringify({
                "big_case": blocks[0], "line_case": blocks[1], "case": blocks[2], "id": id, "uuid": uuid
            }));
        });
    });
</script>
{% endblock %}